compare_CFL:
  activate: True
  scheme_name: 'Schema-Roe'
  fields: ['Temperature', 'Mach']

compare_scheme:
  activate: True
  schemes_names: ['Schema-Roe', 'Schema-Rusanov']
  fields: ['Temperature', 'Mach']
  comp_multi_cfl: True
  target_cfl: null
